### ISSUE TITLE
Пророзиції

### ISSUE THREAD

**Issue by Esentiel** [zbroyar/mass_killings#1]
Привіт.

1. переклад англійською потрібен.
2. потрібно зберегти усю фнформацію, яка зараз надається за посиланнями, т.к. її можуть видалити і посилання будуть недійсні.
3. 
Дякую.

**Comment by zbroyar** [comment]
1. Переклад робиться.
2. Із задоволенням прийму PR з скріншотами/файлами. Але. Виступ Хазіна, якщо що, у мене збережений локально, інше скоріш за все вже напевно є у WebArchive.

**Comment by es5entia** [comment]
Я би додав що попередня планування атакувати міста градами та іншою зброєю массового ураження сто відсотково означало планування смертність багатої кількості цивільних

**Comment by zbroyar** [comment]
Штука в тому, що вони як-раз не планували з нами всерйоз воювати. Згідно їхніх, та й багатьох західних, розрахунків ми мали посипатись протягом 72 годин.

**Comment by troyane** [comment]
Є https://github.com/zbroyar/mass_killings/pull/3

**Comment by zbroyar** [comment]
Приклав.

**Comment by troyane** [comment]
@zbroyar 
Для перекладу (не лише на англійську, а на кілька мав одночасно + з відслідкуванням змін у оригінальному файлі) зручно скористатися тулзою -- https://gitlocalize.com/

Реєструйтеся, логіньтеся з credentials від github, там далі інтуїтивно все.

**Comment by zbroyar** [comment]
Дякую, зареєструвався.

**Comment by zbroyar** [comment]
Дякую, дивлюсь.
