### ISSUE TITLE
90 відсотків втрат

### ISSUE THREAD

**Issue by artemoliynyk** [zbroyar/mass_killings#13]
https://github.com/zbroyar/mass_killings/blob/229ff4cd514e3f29840c35fb68b045594e512f2f/Cleansing.md?plain=1#L63

Поясність, будь ласка, що значить ці 90%?
> повні втрати на рівні 90% від загальної чисельності угруповання, що є нереальним.

**Comment by zbroyar** [comment]
Я не зрозумів питання, уточніть його, будь ласка.

**Comment by artemoliynyk** [comment]
ОК, намагаюсь зрозуміти як ці 90% рахуються

**Comment by bona-fide-supraman** [comment]
@artemoliynyk Рекомендую https://learning-media.allogy.com/api/v1/pdf/59ca4340-e2f2-4a1d-92d9-ee0398092628/contents
Порівнювати російську армію з американською не слід, алеж навіть їм в бойових втратах в сучасних війнах приблизно від 9 (Ірак) до 20% (WW2) усіх бойових втрат спричиняючих небоєздатність підрозділів становлять втрати загиблими (в тім від ран та на полі бою).
