### ISSUE TITLE
Задача: перевірити розміри масового захоронення в Бучі

### ISSUE THREAD

**Issue by troyane** [zbroyar/mass_killings#16]

**Comment by bona-fide-supraman** [comment]
Матеріали придатні для дальшого аналізу пропоную розміщувати [тут](https://drive.google.com/drive/folders/16NXSYKFDmIBOWSykzhldlRbLLOzlNk7J?usp=sharing). В майбутньому ці матеріали з обробленими даними слід замістити в якомусь окремому каталозі в [цьому сховищі](https://github.com/zbroyar/mass_killings).

**Comment by zbroyar** [comment]
13.153х[3.2-2.4]. Початкову глибину поміряти неможливо, оскільки яма завалена тілами у різних місцях від -1.5м до рівня землі.
