### ISSUE TITLE
Атака міст градами, авіацієй та балістичними\крилатими ракетами

### ISSUE THREAD

**Issue by es5entia** [zbroyar/mass_killings#2]
Я би додав що попереднє планування атакувати міста градами та іншою зброєю массового ураження сто відсотково означало планування смертності багатої кількості цивільних

**Comment by zbroyar** [comment]
У тому-то і штука, що вони не планували зносити міста РСЗО. Вони планували звалити нас щелбаном і далі спокійно зачищати всіх носіїв українства.
