### ISSUE TITLE
Додати посилання на статтю до основного документу

### ISSUE THREAD

**Issue by Solitudinem** [zbroyar/mass_killings#24]
Росіяни поставили на автопублікування 26 лютого сттатю про приєднання України і сервер ria ru автоматично запостив її. Публікацію видалили, вона є в архіві https://web.archive.org/web/20220226051154/https://ria.ru/20220226/rossiya-1775162336.html

**Comment by zbroyar** [comment]
Додав, дякую. Це правда дуже цікавий випадок.
