### ISSUE TITLE
Перехоплений німецькою BND радіотрафік про вбивство цивільних осіб

### ISSUE THREAD

**Issue by judaew** [zbroyar/mass_killings#32]
Перехоплений німецькою федеральною розвідувальною службою (BND) радіотрафік про вбивство цивільних осіб. На цьому радіотрафику обговорювалися вбивства цивільних осіб, тому отримати нам запис від німців цього радіотрафику може бути дуже корисним.

Німецька стаття на Spiegel, котра про це писала: [Russische Soldaten besprachen Gräueltaten gegen Zivilisten über Funk](https://www.spiegel.de/politik/ukraine-butscha-soldaten-besprachen-graeueltaten-gegen-zivilisten-ueber-funk-a-9e01662c-aa7e-4828-bf6f-f662d9b6164e).

**Comment by zbroyar** [comment]
Дякую, я бачив, але це трошки інше, а саме безпосереднє свідчення злочину. Дослідження - про те, що цей злочин було сплановано.
