### ISSUE TITLE
Документи про плани захвата Києва

### ISSUE THREAD

**Issue by judaew** [zbroyar/mass_killings#35]
Ці документи здобуті нашою розвідкою про те, як росія планувала під виглядом стратегічних військових навчань захопити Україну. На документах стоїть наступна дата 23.02.2022, себто за добу до повномасштабної війни. Я гадаю, що це може бути додано до нашого документа як заздалегідь сплановані плани.

[Пост на Facebook](https://www.facebook.com/DefenceIntelligenceofUkraine/posts/291457466499014), посилання на документ в [Google Docs](https://drive.google.com/file/d/1YWwcAHKTllB4DK6FWFan5a88A8fBK3o7/view).

**Comment by zbroyar** [comment]
Дякую, зараз почитаю.

**Comment by zbroyar** [comment]
Мені не подобається цей документ: там є кілька нестиковок, які натякають, що це може бути фейк. Наприклад, Бойове Розпорядження, згідно шапки, виписане 23.02 о 20:00, але при цьому у самому документі читаємо:

> … к 14.00 23.02.2022 года, развернуть систему разведки…

Тобто, БР-ка пропонує розгорнути за 8 годин до віддачі розпорядження. Такі документи у роботі користувати не можна.

**Comment by judaew** [comment]
Добре, дякую за ваші міркування.
