### ISSUE TITLE
Інфа корисна

### ISSUE THREAD

**Issue by dzhgenti** [zbroyar/mass_killings#4]
Дякую за аналіз і надану інформацію. Але cleansing.org потрібно прибрати з назви файлу. Не знаю що було на цій сторінці до сьогодні, але інформація про продаж цього домену за $10к наштовхує на думки, що автор за рахунок болючої теми хоче отримати трафік. Перегляд історії домену в archive.org не надав якоїсь впевненності що домен щойно заекспайрився і все просто співпадіння...

**Comment by zbroyar** [comment]
Я не хочу використовувати термін "геноцид", бо він має досить точне значення. У данному випадку ми маємо справу із, скоріше, україноцидом, тобто винищенням носіїв української ідеї, здатних опиратись.

До того-ж, прямо зараз ми судимось з РФ у міжнародному суді з приводу неправомірного використання терміну “геноцид” для виправдання агресії.

**Comment by zbroyar** [comment]
@dzhgenti ви побачили зраду там, де її нема: .org це розширення для файлів у форматі OrgMode, див. https://orgmode.org

І full disclosure: я не маю жодного відношення до згаданого вами домену.

**Comment by dzhgenti** [comment]
Впевнений що назву можна підібрати. Наприклад "Документовані плани РФ по знищенню українців". @zbroyar виправляєм зраду швидше ))

**Comment by zbroyar** [comment]
Ви знайшли зраду там, де її нема: розширення файлу .org має говорити моєму Emacs’у про те, що це - текстовий файл у певному форматі. Дивіться https://orgmode.org
