### ISSUE TITLE
Можливість додати шведську мову

### ISSUE THREAD

**Issue by iChester** [zbroyar/mass_killings#41]
Якщо є така потреба, товариш може долучитись до перекладу матеріалів шведською мовою. Контакт наразі через мене

**Comment by troyane** [comment]
@iChester дякуємо, так, це буде дуже добре. Додамо. Як буде додано, я відпишу тут.

**Comment by troyane** [comment]
@iChester готово -- https://gitlocalize.com/repo/7294/sv/Cleansing.md

Дайте акаунт товариша, назначу його модератором.
