### ISSUE TITLE
Неправильне посилання на GitLocalize в інструкції для перекладачів

### ISSUE THREAD

**Issue by iChester** [zbroyar/mass_killings#42]
В інструкції:
"Заходьте на сторінку проекту в GitLocalize: https://gitlocalize.com/repo/7265"

Проблема:
При переході помилка 404

Має бути:
[https://gitlocalize.com/repo/7294](https://gitlocalize.com/repo/7294)

**Comment by troyane** [comment]
Дякую, виправимо.

**Comment by troyane** [comment]
Готово, дякую за пильність!
