### ISSUE TITLE
додайте опис репозиторію, щоб більше інфо було видно у превʼю в твітері, телеграмі, тощо

### ISSUE THREAD

**Issue by akovantsev** [zbroyar/mass_killings#43]
замість дефолтного "Contribute to zbroyar/mass_killings development by creating an account on GitHub."

тут:
<img width="330" alt="Screen Shot 2022-04-16 at 20 12 18" src="https://user-images.githubusercontent.com/1266939/163684761-102df47f-9edd-41bd-8121-cbf668579e01.png">

**Comment by zbroyar** [comment]
Зараз норм? :-)

**Comment by akovantsev** [comment]
Може додати коротку фразу англійською?
```
Russia PLANNED to kill civilians.
Ми вважаємо, що РФ планувала вбивати цивільних ...
```

Українці це і так знають, а розповсюджувати треба на решту світу

**Comment by zbroyar** [comment]
Куди саме ви пропонуєте її додати?

**Comment by akovantsev** [comment]
в той же текст, замість червоної лінії
<img width="396" alt="Screen Shot 2022-04-24 at 13 56 11" src="https://user-images.githubusercontent.com/1266939/164973144-93ff8e6d-0478-4749-a687-574de2fc7fec.png">

**Comment by zbroyar** [comment]
Вже не зможу: це частина назви проекту, яка у свою чергу є частиною посилання на всі документи у проекті. А ці посилання вже розійшлись дуже широко і мають працювати.

**Comment by akovantsev** [comment]
маю на увазі туди же - в опис:

**Comment by zbroyar** [comment]
Це на якій саме сторінці нема опису? Дайте урл, будь ласка.

**Comment by akovantsev** [comment]
:D це скріншот з самого першого повідомлення 
додати якийсь текст англійською в about репозиторія https://github.com/zbroyar/mass_killings

<img width="400" alt="Screen Shot 2022-04-24 at 14 04 47" src="https://user-images.githubusercontent.com/1266939/164973428-580122c8-de17-4d61-88a0-b45f9ec522c8.png">

**Comment by zbroyar** [comment]
А, зрозумів, зараз спробую.

**Comment by zbroyar** [comment]
Норм? :-)
