### ISSUE TITLE
Переклад італійською

### ISSUE THREAD

**Issue by Clanato** [zbroyar/mass_killings#44]
Хочу допомогти з перекладом на італійську, будь ласка, додайте цю мову

**Comment by troyane** [comment]
Дякую вам, @Clanato! Ось -- https://gitlocalize.com/repo/7294/it/Cleansing.md, до роботи!

**Comment by zbroyar** [comment]
Для довідки, у нас є ось такий переклад, але він точно застарілий.

[Documento (39).pdf](https://github.com/zbroyar/mass_killings/files/8500698/Documento.39.pdf)
