### ISSUE TITLE
"Submit" translation section via GitLocalize doesn't work

### ISSUE THREAD

**Issue by troyane** [zbroyar/mass_killings#45]
Click on the "Submit" button makes it disabled and remains the same:

![image](https://user-images.githubusercontent.com/477468/163685931-34ce4908-01fd-43aa-a6d4-a009f7403e1e.png)

No changes to text saved.

@ilyaspiridonov, is it related to the known issue?

**Comment by paul1974nsac** [comment]
Duplicate of #45

**Comment by igorbrigadir** [comment]
This seems to work for me now, i can submit successfully.
