### ISSUE TITLE
Запит на права модератора англійської

### ISSUE THREAD

**Issue by iChester** [zbroyar/mass_killings#49]
Доброго дня! Прошу права модерації англомовних матеріалів проєкта. Маю диплом філолога і спеціалізуюсь саме на перекладах.

**Comment by troyane** [comment]
Привіт, @iChester! Дякую за увагу до проекту. Додав до модераторів.
Хочу зазначити, що зараз ми зіткнулися з технічими труднощами на проекті GitLocalize:
- https://github.com/zbroyar/mass_killings/issues/45
- https://github.com/zbroyar/mass_killings/issues/31

Тому ви можете бачити несинхронізовані дані на сторінках відповідних перекладів. Щоб уникнути зайвої роботи, про всяк випадок перегляньте файл перекладу англійською тут -- https://github.com/zbroyar/mass_killings/blob/master/en/Cleansing.md, і використовуйте його як базу.
