### ISSUE TITLE
I want to help with the translation into Slovak

### ISSUE THREAD

**Issue by edgeMonnie** [zbroyar/mass_killings#54]
I would like to help with translation into Slovak language, please add this language. Thanks!

**Comment by troyane** [comment]
Hello @edgeMonnie! Thanks for your interest and willingness to help.

Here is the Slovak translation (pre-translated by machine): https://gitlocalize.com/repo/7294/sk/Cleansing.md

You are assigned as moderator of the Slovak translation.
